sudo: required
services:
  - docker
before_install:
  - docker build -t karthikawebon/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true karthikawebon/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-472323887720"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY