FROM node:alpine

WORKDIR /usr/app

COPY ./package.json /usr/app
#RUN npm config set registry http://registry.npmjs.org/
RUN npm config set registry http://registry.npmjs.org/
RUN npm i

COPY ./ /usr/app

CMD ["npm", "start"]